/** Types de clients — logistique, fret et opérations humanitaires */
export const CLIENT_LOGISTICS_CATEGORIES = [
  { value: 'Aide humanitaire', label: 'Aide humanitaire' },
  { value: 'ONG internationale', label: 'ONG internationale' },
  { value: 'Organisme international', label: 'Organisme international (ONU, bailleurs…)' },
  { value: 'Transitaire', label: 'Transitaire' },
  { value: 'Compagnie maritime', label: 'Compagnie maritime' },
  { value: 'Compagnie aérienne', label: 'Compagnie aérienne' },
  { value: 'Armateur', label: 'Armateur' },
  { value: 'Agent maritime', label: 'Agent maritime' },
  { value: 'Agent de fret aérien', label: 'Agent de fret aérien (GSA)' },
  { value: 'Importateur', label: 'Importateur' },
  { value: 'Exportateur', label: 'Exportateur' },
  { value: 'Chargeur', label: 'Chargeur (Shipper)' },
  { value: 'Destinataire', label: 'Destinataire (Consignee)' },
  { value: 'Donneur d\'ordre', label: 'Donneur d\'ordre' },
  { value: 'Affréteur', label: 'Affréteur' },
  { value: 'Commissionnaire de transport', label: 'Commissionnaire de transport' },
  { value: 'Logisticien', label: 'Logisticien / 3PL' },
  { value: 'Transporteur routier', label: 'Transporteur routier' },
  { value: 'Entrepôt sous douane', label: 'Entrepôt sous douane' },
  { value: 'Courtier en douane', label: 'Courtier en douane' },
  { value: 'Administration publique', label: 'Administration publique' },
  { value: 'Entreprise privée', label: 'Entreprise privée' },
  { value: 'Autre', label: 'Autre' },
] as const;
