-- Colonne abonnement sur les types de charges
ALTER TABLE public."CHARGES"
  ADD COLUMN IF NOT EXISTS "abonnement" text NULL;

-- Mouvements de provision par charge (appro / sortie)
CREATE TABLE IF NOT EXISTS public."CHARGE_PROVISION" (
  "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Charge" text,
  "Date_operation" date,
  "Type_operation" text,
  "Numero_facture" text,
  "Montant" numeric,
  "Solde" numeric,
  "Reference" text
);

ALTER TABLE public."CHARGE_PROVISION"
  ADD COLUMN IF NOT EXISTS "Reference" text;

CREATE INDEX IF NOT EXISTS "idx_charge_provision_charge"
  ON public."CHARGE_PROVISION" ("Charge");

CREATE INDEX IF NOT EXISTS "idx_charge_provision_type"
  ON public."CHARGE_PROVISION" ("Type_operation");

ALTER TABLE public."CHARGE_PROVISION" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_read_charge_provision" ON public."CHARGE_PROVISION"
  FOR SELECT USING (true);

CREATE POLICY "allow_insert_charge_provision" ON public."CHARGE_PROVISION"
  FOR INSERT WITH CHECK (true);

CREATE POLICY "allow_update_charge_provision" ON public."CHARGE_PROVISION"
  FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "allow_delete_charge_provision" ON public."CHARGE_PROVISION"
  FOR DELETE USING (true);
