-- Table clients (référentiel pour le champ Client des factures)
CREATE TABLE IF NOT EXISTS public.clients (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nom character varying NULL,
  pays_sige character varying NULL,
  categorie character varying NULL,
  statut boolean NULL DEFAULT true,
  adresse_facturation text NULL,
  created_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS clients_nom_idx ON public.clients (lower(btrim(nom)));
